version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "19090:9000"  # API порт
      - "19091:9001"  # Веб-интерфейс
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

  app:
    build: . 
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_started
      prefect-server:
        condition: service_started
      minio:
        condition: service_started
    command: sleep infinity 

  prefect-server:
    image: prefecthq/prefect:2-latest
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200" # Пробрасываем порт веб-интерфейса на ваш компьютер
    volumes:
      - prefectdata:/root/.prefect
    depends_on:
      - postgres

  prefect-worker:
    #build: . 
    image: prefecthq/prefect:2-latest
    restart: always
    command: prefect worker start --pool 'default-agent-pool'
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432    
    depends_on:
      - prefect-server


volumes:
  pgdata:
  miniodata:
  prefectdata: