version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=project_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "19090:9000"  # API порт
      - "19091:9001"  # Веб-интерфейс
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

  app:
    build: . # Собрать образ из Dockerfile в текущей директории
    volumes:
      - .:/app # Монтируем локальную папку с кодом внутрь контейнера
    depends_on:
      - postgres
      - minio
    command: sleep infinity 

volumes:
  pgdata:
  miniodata: